### ISSUE TITLE
Change Color of Selected String after '@'

### ISSUE THREAD

**Issue by SunilGauswami** [mattlewis92/angular-text-input-autocomplete#1]
How i can change color or make it bold select string after @ in normal text area field. Like @Sunil Gauswami >> blue.
Example : http://prntscr.com/iu4vzr

**Comment by mattlewis92** [comment]
The only way you can do rich html text areas is by using contenteditable, however the browser API's are really bad for this, so you would be better off by adapting a wysiwyg editor, and hide the toolbar, but use its rich textarea functionality to do the highlighting. Something like http://prosemirror.net/ maybe.
