### ISSUE TITLE
How to find object and display name?

### ISSUE THREAD

**Issue by quoctu2016** [mattlewis92/angular-text-input-autocomplete#2]
const names = [

  {id: 1, name: 'Reda Marriott'},

  {id: 1, name: 'Cleta Cheatwood'},

  {id: 1, name: 'Penney Fortman'},

];

**Comment by mattlewis92** [comment]
Hi there, you can achieve this by using a custom menu component: https://stackblitz.com/edit/angular-wgafuw?file=src%2Fapp%2Fmenu.component.ts

Hope that helps! 😄
