### ISSUE TITLE
Scrolling with down arrow not working

### ISSUE THREAD

**Issue by AlMuIssues** [mattlewis92/angular-text-input-autocomplete#6]
Hello,
I have my custom menu. If menu contains more items, the scroll bar appears. In this case scrolling with DOWN_ARROW is not working. In your example I saw the same behavior: 
https://stackblitz.com/edit/angular-wgafuw?file=src%2Fapp%2Fapp.component.ts

**Comment by mattlewis92** [comment]
Thanks for reporting, should be fixed now in `0.2.1` 😄
