### ISSUE TITLE
Not working in ionic3 angular5

### ISSUE THREAD

**Issue by aanandk** [mattlewis92/angular-text-input-autocomplete#7]
Auto suggestion is not working for ionic3-android build, but working in browser. Can you let me know the fix for ionic android build?

**Comment by mattlewis92** [comment]
Sorry but I don't have an android phone or use ionic. It sounds like an android browser bug which can usually be resolved by using crosswalk for android: https://medium.com/appseed-io/boost-your-ionic-app-performance-with-crosswalk-6d9d083eadbb
